apiVersion: v1
kind: Secret
metadata:
  name: nging-secrets
  namespace: nging
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "12345"
  POSTGRES_DB: postgres
  REDIS_PASSWORD: "12345"
  JWT_SECRET: my-super-secret-key-for-jwt-demo-at-least-32-bytes
